title: Programming blog
author: korobenkoss
email: korobenkoss@live.com
description: > # this means to ignore newlines until "baseurl:"
  personal, blog, programming, web development, html, css, javascript

# social links
twitter_username: korobenkoss # DO NOT include the @ character, or else the build will fail!
github_username:  korobenkoss # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
